# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"


gem "rubocop", "~> 1.18"

gem "reek", "~> 6.0"

gem "rcodetools", "~> 0.8.5"

gem "ruby-debug-ide", "~> 0.7.2"

gem "solargraph", "~> 0.42.3"

gem "test-unit", "~> 3.4"

gem "rspec", "~> 3.10"
